#!/bin/sh
# usage:
#   delete-ovpn-single-user
#

docker run --rm -it --volumes-from wink-ovpn-data --volume /tmp/openvpn_clients:/etc/openvpn/clients kylemanna/openvpn /etc/openvpn/delete-ovpn-user.sh $1

